// Blog posts about receipt scanning (Advanced plan). Same shape as POSTS in
// src/pages/Blog.jsx; each slug also needs a /p/ rewrite in vercel.json and a
// sitemap entry so it is pre-rendered and discovered.

const ADVANCED_TRIAL_CTA_NL = {
  title: "Probeer bonnetjes scannen 7 dagen gratis",
  sub: "Advanced: bon scannen, offertes, btw-overzicht per kwartaal en meer. Daarna €19 per maand excl. btw, altijd opzegbaar.",
  button: "Start 7 dagen gratis →",
  plan: "business",
};

const RECEIPT_POSTS = [
  {
    slug: "bonnetjes-scannen-app-zzp",
    lang: "nl",
    title: "Bonnetjes scannen als zzp'er: van foto naar uitgave in een paar seconden",
    seoTitle: "Bonnetjes scannen app voor zzp'ers | FaturaPro",
    description: "Maak een foto van je bon en FaturaPro vult datum, leverancier, bedrag en btw automatisch in. Zo werkt bonnetjes scannen, stap voor stap.",
    date: "2026-10-01",
    readTime: "6 min",
    keywords: "bonnetjes scannen app, bonnen scannen zzp, bonnetjes app zzp, kassabon scannen, bonnetjes digitaliseren, uitgaven bijhouden zzp, btw bonnetjes",
    quickAnswer: "Open in FaturaPro de pagina Uitgaven, kies Uitgave toevoegen en tik op Bon toevoegen. Maak een foto of kies een pdf. Binnen een paar seconden staan datum, leverancier, omschrijving, categorie, valuta, bedrag excl. btw en btw-tarief ingevuld. Jij controleert en slaat op, en de bon blijft bij de uitgave bewaard. Bonnetjes scannen zit in het Advanced-plan (€19 per maand excl. btw, 7 dagen gratis te proberen).",
    checklist: [
      "Uitgaven → Uitgave toevoegen → Bon toevoegen",
      "Maak een foto van de bon of kies een pdf (max. 5 MB)",
      "Datum, leverancier, bedrag en btw worden automatisch ingevuld",
      "Controleer de gegevens en sla op",
      "De bon blijft bij de uitgave: open hem via het paperclip-icoon",
      "De betaalde btw telt mee in je btw-overzicht per kwartaal",
    ],
    sections: [
      { h: "Waarom losse bonnetjes je geld kosten", p: "Een bonnetje dat kwijtraakt, is een kostenpost die je niet kunt aftrekken en btw die je niet terugvraagt. Toch belanden bonnen in jaszakken, dashboardkastjes en schoenendozen, omdat het overtypen ervan saai is en je het uitstelt tot de btw-aangifte eraan komt. Door een bon meteen te fotograferen en te verwerken, verdwijnt dat uitstelmoment: de uitgave staat erin voordat je de winkel uit bent." },
      { h: "Zo werkt bonnetjes scannen in FaturaPro", p: "Ga naar Uitgaven en kies Uitgave toevoegen. Bovenin het venster staat het vak Bon. Tik op Bon toevoegen: op je telefoon kun je direct een foto maken, op je computer kies je een foto of pdf. Terwijl FaturaPro de bon leest, zie je 'Bon wordt gelezen…'. Daarna zijn de velden ingevuld en staat er in het groen dat je de gegevens even moet controleren. Klopt alles, dan kies je Uitgave toevoegen." },
      { h: "Wat wordt er automatisch ingevuld?", p: "FaturaPro leest de datum, de leverancier, een korte omschrijving, de categorie, de valuta, het bedrag exclusief btw en het btw-tarief. Staan er meerdere btw-tarieven op één bon, zoals 9% en 21% in de supermarkt, dan rekent FaturaPro het gemiddelde tarief uit, zodat het totale btw-bedrag klopt. Een bon in dollars of ponden krijgt automatisch de juiste valuta, en die blijft in je overzichten apart van je euro's." },
      { h: "Controleer altijd even", p: "FaturaPro vult alleen in wat op de bon staat en raadt geen bedragen die er niet op staan. Is een foto wazig of is het document geen bon, dan zie je dat meteen en vul je de gegevens zelf in. De uitgave wordt pas opgeslagen als jij op opslaan tikt, dus je houdt altijd de controle over je administratie." },
      { h: "Waar blijft je bon?", p: "De bon wordt afgeschermd opgeslagen bij de uitgave. Alleen jij en je teamleden kunnen hem openen, via het paperclip-icoon naast de uitgave. Maak je een fout, dan kun je de bon vervangen of verwijderen; verwijder je de uitgave, dan verdwijnt ook de bon. Sluit je het venster zonder op te slaan, dan wordt de geüploade foto direct weer verwijderd." },
      { h: "Van bon naar btw-overzicht", p: "Elke uitgave die je opslaat, telt mee in het btw-overzicht per kwartaal op de pagina Uitgaven. Daar zie je de btw op je verkopen, de btw die je zelf hebt betaald en wat je per saldo moet betalen of terugkrijgt, per valuta. Met één klik exporteer je de uitgaven van een kwartaal als CSV voor je boekhouder. FaturaPro doet zelf geen btw-aangifte; het overzicht helpt je die snel en goed in te vullen." },
      { h: "Tips voor een goede foto", p: "Leg de bon plat op een donkere ondergrond, zorg voor voldoende licht en zet de hele bon in beeld, inclusief de datum en het btw-deel onderaan. Vouw kreukels zo veel mogelijk glad. Scan kassabonnen van thermisch papier snel: de inkt vervaagt na een paar maanden, en een onleesbare bon helpt je later niets meer." },
      { h: "Voor wie is bonnetjes scannen handig?", p: "Vooral voor zzp'ers met veel kleine kosten: bouw- en klusbedrijven die dagelijks bij de bouwmarkt staan, creatieven die materiaal en software kopen, en consultants met reis- en lunchkosten. Hoe meer bonnen je hebt, hoe meer typwerk je bespaart en hoe minder aftrekbare btw je mist. Samen met offertes, terugkerende facturen en het btw-overzicht zit het in het Advanced-plan." },
    ],
    faqs: [
      { q: "Mag ik de papieren bon weggooien na het scannen?", a: "De Belastingdienst staat toe dat je bonnen digitaal bewaart, als de kopie volledig, leesbaar en ongewijzigd is. Controleer daarom of alle gegevens goed zichtbaar zijn voordat je het origineel weggooit, en kijk bij twijfel naar de officiële regels voor jouw situatie." },
      { q: "Welke bestanden kan ik uploaden?", a: "Foto's (jpg, png, webp) en pdf-bestanden tot 5 MB. Foto's worden voor het uploaden automatisch verkleind, zodat het snel gaat." },
      { q: "Werkt het ook met buitenlandse bonnen?", a: "Ja. FaturaPro herkent de valuta op de bon en houdt die in het btw-overzicht apart van andere valuta." },
      { q: "Doet FaturaPro mijn btw-aangifte?", a: "Nee. FaturaPro geeft je per kwartaal een overzicht van de btw op je verkopen en je kosten. De aangifte doe je zelf of via je boekhouder bij de Belastingdienst." },
      { q: "Wat kost bonnetjes scannen?", a: "Het zit in het Advanced-plan van €19 per maand excl. btw. Je kunt Advanced 7 dagen gratis proberen en daarna op elk moment opzeggen." },
    ],
    sources: [
      { label: "Belastingdienst: uw facturen bewaren", href: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/administratie_bijhouden/facturen_maken/uw_facturen_bewaren" },
    ],
    relatedLinks: [
      { label: "Bonnetjes bewaren: hoe lang en mag een foto?", href: "/blog/bonnetjes-bewaren-belastingdienst" },
      { label: "Btw terugvragen op je kosten", href: "/blog/btw-terugvragen-kosten-zzp" },
      { label: "FaturaPro in het Nederlands", href: "/nl" },
    ],
    cta: ADVANCED_TRIAL_CTA_NL,
  },
  {
    slug: "bonnetjes-bewaren-belastingdienst",
    lang: "nl",
    title: "Bonnetjes bewaren: hoe lang, en mag een foto? (Belastingdienst 2026)",
    seoTitle: "Bonnetjes bewaren: regels van de Belastingdienst | FaturaPro",
    description: "Hoe lang moet je als ondernemer bonnetjes bewaren, mag een foto of scan en wat moet er leesbaar zijn? De regels, plus een simpele routine.",
    date: "2026-10-01",
    readTime: "6 min",
    keywords: "bonnetjes bewaren, bonnetjes bewaren belastingdienst, bewaarplicht zzp, bonnetjes digitaal bewaren, hoe lang bonnetjes bewaren, kassabon bewaren zakelijk",
    quickAnswer: "Als ondernemer bewaar je je administratie, inclusief bonnetjes en inkoopfacturen, in de regel 7 jaar; voor gegevens over onroerende zaken geldt 10 jaar. Je mag bonnen digitaal bewaren, bijvoorbeeld als foto of scan, zolang de kopie volledig, leesbaar en ongewijzigd is. Scan kassabonnen snel, want de inkt van thermisch papier vervaagt.",
    checklist: [
      "Bewaartermijn: in de regel 7 jaar, 10 jaar voor onroerende zaken",
      "Een foto of scan mag, als de kopie volledig en leesbaar is",
      "Datum, leverancier, bedrag en btw moeten zichtbaar zijn",
      "Niets aan de kopie veranderen",
      "Thermische kassabonnen zo snel mogelijk scannen",
      "Bewaar bonnen gekoppeld aan de uitgave, niet los in een map",
    ],
    sections: [
      { h: "Waarom de Belastingdienst je bonnetjes wil zien", p: "Met je bonnen en inkoopfacturen onderbouw je de kosten die je aftrekt van je winst en de btw die je als voorbelasting terugvraagt. Bij een controle moet je die kunnen laten zien. Zonder bon kan een kostenpost worden geschrapt en moet je teruggevraagde btw alsnog betalen." },
      { h: "Hoe lang moet je bonnetjes bewaren?", p: "De algemene bewaarplicht voor je administratie is 7 jaar. Voor gegevens over onroerende zaken, zoals een bedrijfspand, geldt 10 jaar. De termijn loopt vanaf het einde van het jaar waarin het document is gemaakt. Een bon van maart 2026 bewaar je dus in elk geval tot en met 2033." },
      { h: "Mag een foto of scan?", p: "Ja. Je mag papieren bonnen en facturen omzetten naar een digitale kopie en die bewaren in plaats van het origineel, zolang de omzetting volledig en juist is. De kopie moet dezelfde inhoud hebben als het origineel en leesbaar blijven gedurende de hele bewaartermijn. Een scherpe foto met je telefoon voldoet daaraan, zolang niets is weggelaten of aangepast." },
      { h: "Wat moet er leesbaar zijn?", p: "Zorg dat de naam van de winkel of leverancier, de datum, wat je hebt gekocht, het totaalbedrag en de btw te lezen zijn. Voor bedragen tot €100 inclusief btw mag een leverancier een vereenvoudigde factuur geven, zoals een kassabon; daarop staan minder gegevens. Is een deel van de bon afgescheurd of vervaagd, dan is de kopie niet volledig." },
      { h: "Het probleem met kassabonnen", p: "Veel kassabonnen zijn gedrukt op thermisch papier. In een warme auto of portemonnee vervaagt die inkt binnen een paar maanden, lang voordat de bewaartermijn om is. Een bon die je pas bij de btw-aangifte terugvindt, is dan vaak al onleesbaar. De enige echte oplossing is scannen op het moment dat je de bon krijgt." },
      { h: "Een routine die wél werkt", p: "Maak van bonnen verwerken een gewoonte van tien seconden: bon ontvangen, foto maken, klaar. Bewaar de foto bij de uitgave zelf, zodat je bij een vraag van je boekhouder of de Belastingdienst niet hoeft te zoeken in een map met honderden losse afbeeldingen. Verwerk wat je toch op papier verzamelt minstens één keer per week." },
      { h: "Zo doe je het in FaturaPro", p: "In het Advanced-plan van FaturaPro maak je bij een nieuwe uitgave een foto van de bon. Datum, leverancier, bedrag en btw worden automatisch ingevuld en de bon blijft afgeschermd bij de uitgave bewaard, te openen via het paperclip-icoon. De betaalde btw telt direct mee in je btw-overzicht per kwartaal." },
    ],
    faqs: [
      { q: "Moet ik het papieren origineel ook bewaren?", a: "Nee, als je digitale kopie volledig, juist en leesbaar is, mag je die bewaren in plaats van het origineel. Controleer de kopie voordat je het papier weggooit." },
      { q: "Tellen bonnetjes zonder btw-vermelding mee?", a: "Voor je winst kun je zakelijke kosten meestal onderbouwen met een bon. Om btw terug te vragen heb je een factuur of vereenvoudigde factuur nodig waarop de btw te herleiden is. Vraag bij twijfel om een factuur op je bedrijfsnaam." },
      { q: "Hoe lang bewaart FaturaPro mijn bonnen?", a: "Je bonnen blijven bij je uitgaven staan zolang je ze niet zelf verwijdert. Je blijft zelf verantwoordelijk voor je bewaarplicht; exporteer daarom ook regelmatig je gegevens voor je eigen administratie." },
    ],
    sources: [
      { label: "Belastingdienst: uw facturen bewaren", href: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/administratie_bijhouden/facturen_maken/uw_facturen_bewaren" },
    ],
    relatedLinks: [
      { label: "Bonnetjes scannen met FaturaPro", href: "/blog/bonnetjes-scannen-app-zzp" },
      { label: "Btw terugvragen op je kosten", href: "/blog/btw-terugvragen-kosten-zzp" },
      { label: "FaturaPro in het Nederlands", href: "/nl" },
    ],
    cta: ADVANCED_TRIAL_CTA_NL,
  },
  {
    slug: "btw-terugvragen-kosten-zzp",
    lang: "nl",
    title: "Btw terugvragen op je kosten als zzp'er: zo mis je geen voorbelasting",
    seoTitle: "Btw terugvragen op kosten als zzp'er | FaturaPro",
    description: "De btw op je zakelijke kosten mag je vaak aftrekken als voorbelasting. Wanneer kan dat, wat heb je nodig en hoe voorkom je dat je geld laat liggen?",
    date: "2026-10-01",
    readTime: "7 min",
    keywords: "btw terugvragen zzp, voorbelasting aftrekken, btw aftrekken kosten, btw terugvragen bonnetjes, btw-aangifte zzp kosten, voorbelasting zzp",
    quickAnswer: "Ben je btw-plichtig, dan mag je de btw op zakelijke kosten meestal aftrekken als voorbelasting in je btw-aangifte. Daarvoor heb je een factuur of vereenvoudigde factuur (tot €100) nodig waarop de btw staat. Doe je mee aan de kleineondernemersregeling (KOR), dan vraag je geen btw terug. Wie bonnen kwijtraakt, laat dus letterlijk geld liggen.",
    checklist: [
      "Alleen als je btw-plichtig bent (niet met de KOR)",
      "De kosten zijn zakelijk (bij gemengd gebruik: alleen het zakelijke deel)",
      "Je hebt een factuur of kassabon waarop de btw staat",
      "Je trekt de btw af in de aangifte over de periode van de factuur",
      "Btw op je verkopen min voorbelasting = te betalen of terug te krijgen",
    ],
    sections: [
      { h: "Wat is voorbelasting?", p: "Voorbelasting is de btw die jij als ondernemer betaalt op je zakelijke inkopen en kosten, zoals een laptop, software, materiaal of een zakelijke treinreis. In je btw-aangifte trek je die af van de btw die je over je eigen facturen hebt gerekend. Het verschil betaal je aan de Belastingdienst, of je krijgt het terug als je meer btw hebt betaald dan ontvangen." },
      { h: "Wanneer mag je btw aftrekken?", p: "Je moet btw-plichtig zijn en de kosten moeten zakelijk zijn. Gebruik je iets zowel zakelijk als privé, dan trek je alleen het zakelijke deel af. Voor sommige kosten gelden beperkingen, bijvoorbeeld voor eten en drinken of voor zaken die je ook privé gebruikt. Doe je mee aan de kleineondernemersregeling (KOR), dan reken je geen btw en vraag je ook geen btw terug." },
      { h: "Welk bewijs heb je nodig?", p: "Voor aftrek heb je een factuur nodig waarop de btw staat. Voor bedragen tot €100 inclusief btw mag de leverancier een vereenvoudigde factuur geven, zoals een kassabon met btw. Voor grotere bedragen vraag je om een volledige factuur op je bedrijfsnaam. Zonder bon of factuur kun je de btw niet onderbouwen, en bij een controle moet je die alsnog betalen." },
      { h: "De drie fouten die zzp'ers geld kosten", p: "Eén: bonnen van kleine bedragen niet bewaren, omdat 'die paar euro' niet de moeite lijkt. Bij elkaar is dat per kwartaal vaak tientallen euro's btw. Twee: bonnen pas bij de aangifte zoeken, als ze al vervaagd of kwijt zijn. Drie: btw op een verkeerd tarief of een verkeerd bedrag invoeren, waardoor je aangifte niet klopt. Een vaste routine en een tool die de bedragen van de bon overneemt, voorkomen alle drie." },
      { h: "Per kwartaal: zo reken je het uit", p: "Tel de btw op al je verkoopfacturen van het kwartaal op. Tel daarna de btw op al je zakelijke kosten van dat kwartaal op. Btw op verkopen min voorbelasting is het bedrag dat je betaalt; is het negatief, dan krijg je geld terug. De aangifte en betaling moeten binnen zijn vóór het einde van de maand na het kwartaal, dus voor het derde kwartaal uiterlijk 31 oktober." },
      { h: "Zo houd je het bij in FaturaPro", p: "In het Advanced-plan van FaturaPro maak je een foto van elke bon; de btw wordt overgenomen en de bon blijft bij de uitgave. Op de pagina Uitgaven zie je per kwartaal en per valuta de btw op je facturen, de betaalde btw op je kosten en wat je moet betalen of terugkrijgt. Die bedragen neem je over in Mijn Belastingdienst Zakelijk of geef je aan je boekhouder. FaturaPro doet de aangifte niet voor je." },
    ],
    faqs: [
      { q: "Mag ik btw terugvragen als ik de KOR gebruik?", a: "Nee. Met de kleineondernemersregeling reken je geen btw aan klanten en vraag je ook geen btw terug op je kosten." },
      { q: "Kan ik btw terugvragen op een kassabon?", a: "Voor bedragen tot €100 inclusief btw geldt een kassabon met btw als vereenvoudigde factuur. Voor hogere bedragen vraag je om een factuur op je bedrijfsnaam." },
      { q: "Wat als ik een bon kwijt ben?", a: "Vraag de leverancier om een kopie van de factuur of zoek de digitale factuur in je e-mail of account. Zonder bewijs kun je de btw niet onderbouwen." },
      { q: "Berekent FaturaPro mijn btw-aangifte?", a: "FaturaPro Advanced toont per kwartaal de btw op je verkopen en je kosten, zodat je de aangifte snel kunt invullen. De aangifte zelf doe je bij de Belastingdienst." },
    ],
    sources: [
      { label: "Belastingdienst: uw facturen bewaren", href: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/administratie_bijhouden/facturen_maken/uw_facturen_bewaren" },
      { label: "Business.gov.nl: VAT rates and schemes", href: "https://business.gov.nl/regulations/vat/" },
    ],
    relatedLinks: [
      { label: "Bonnetjes scannen met FaturaPro", href: "/blog/bonnetjes-scannen-app-zzp" },
      { label: "Bonnetjes bewaren: de regels", href: "/blog/bonnetjes-bewaren-belastingdienst" },
      { label: "FaturaPro in het Nederlands", href: "/nl" },
    ],
    cta: ADVANCED_TRIAL_CTA_NL,
  },
  {
    slug: "receipt-scanner-app-freelancers-netherlands",
    lang: "en",
    title: "Receipt Scanner for Freelancers in the Netherlands: Snap, Check, Done",
    seoTitle: "Receipt Scanner App for Freelancers in the Netherlands | FaturaPro",
    description: "Photograph a receipt and FaturaPro fills in the date, supplier, amount and Dutch VAT. How receipt scanning works, how long to keep receipts and how it feeds your VAT summary.",
    date: "2026-10-01",
    readTime: "6 min",
    keywords: "receipt scanner app Netherlands, receipt scanning freelancer, expense tracking ZZP English, scan receipts VAT Netherlands, bookkeeping app English Netherlands, keep receipts Belastingdienst",
    quickAnswer: "In FaturaPro, open Expenses, choose Add expense and tap Add receipt. Take a photo or pick a PDF, and the date, supplier, description, category, currency, amount excluding VAT and VAT rate fill themselves in. You check the details and save; the receipt stays attached to the expense. Receipt scanning is part of the Advanced plan (€19 per month excl. VAT, free for 7 days).",
    checklist: [
      "Expenses → Add expense → Add receipt",
      "Photo (jpg, png, webp) or PDF up to 5 MB",
      "Date, supplier, amount and VAT are filled in for you",
      "Check the details, then save",
      "Open the receipt later from the paperclip icon on the expense",
      "Keep business records for 7 years; a clear digital copy is allowed",
    ],
    sections: [
      { h: "Why Receipts Slip Through the Cracks", p: "Small receipts pile up in wallets and cars because typing them in is tedious. By the time the quarterly VAT return is due, some are lost and others have faded. Each missing receipt is a cost you cannot deduct and VAT you cannot reclaim, so processing receipts the moment you get them pays for itself." },
      { h: "How Receipt Scanning Works in FaturaPro", p: "Go to Expenses and choose Add expense. At the top of the dialog is the Receipt box. Tap Add receipt: on a phone you can take a photo straight away, on a computer you pick a photo or PDF. While FaturaPro reads it you see 'Reading the receipt…', then the form is filled in and a green note asks you to check the details before saving." },
      { h: "What Gets Filled In", p: "FaturaPro reads the date, supplier, a short description, category, currency, amount excluding VAT and the VAT rate. A receipt with mixed rates, such as 9% and 21% at a Dutch supermarket, becomes the effective rate so the VAT total still matches. Foreign receipts keep their own currency, and each currency stays separate in your summaries." },
      { h: "You Stay in Control", p: "Only what is printed on the receipt is filled in; nothing is guessed. If a photo is blurry or not a receipt, you see that straight away and fill the fields yourself. The expense is only saved when you press save, and if you close the dialog the uploaded photo is deleted." },
      { h: "Keeping Receipts for the Belastingdienst", p: "Dutch businesses generally keep their records, including receipts and purchase invoices, for 7 years, and 10 years for real-estate records. A digital copy may replace the paper original when it is complete, accurate and legible. Thermal-paper receipts fade within months, so scanning them right away is the safest way to keep them readable." },
      { h: "From Receipt to Quarterly VAT Summary", p: "Every saved expense counts towards the quarterly VAT summary on the Expenses page: VAT on your sales, VAT paid on costs and the balance to pay or reclaim, per currency. You can export a quarter's expenses as CSV for your accountant. FaturaPro does not file the VAT return; it gives you the figures to file it quickly." },
    ],
    faqs: [
      { q: "Can I throw away the paper receipt after scanning?", a: "The Belastingdienst allows a digital copy instead of the original when the copy is complete, accurate and legible. Check the copy before discarding the paper and follow the official rules for your situation." },
      { q: "Is the app available in English?", a: "Yes. FaturaPro works in English, Dutch, French, Spanish and Arabic, and receipts in any of these languages can be read." },
      { q: "Does FaturaPro file my Dutch VAT return?", a: "No. It shows quarterly VAT figures for your sales and costs; you or your accountant file the return with the Belastingdienst." },
      { q: "How much does receipt scanning cost?", a: "It is included in the Advanced plan at €19 per month excluding VAT, with a 7-day free trial. You can cancel any time." },
    ],
    sources: [
      { label: "Belastingdienst: keeping your invoices (Dutch)", href: "https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/administratie_bijhouden/facturen_maken/uw_facturen_bewaren" },
      { label: "Business.gov.nl: invoice requirements in the Netherlands", href: "https://business.gov.nl/regulations/invoice-requirements/" },
    ],
    relatedLinks: [
      { label: "English invoicing for ZZP'ers", href: "/blog/zzp-invoice-app-english-netherlands" },
      { label: "Compare Free, Essential and Advanced", href: "/blog/invoicing-plans-free-vs-pro-vs-business" },
      { label: "Bonnetjes scannen (Nederlands)", href: "/blog/bonnetjes-scannen-app-zzp" },
    ],
    cta: {
      title: "Try receipt scanning free for 7 days",
      sub: "Advanced: receipt scanning, quotes, quarterly VAT summary and more. Then €19 per month excl. VAT, cancel any time.",
      button: "Start the 7-day trial →",
      plan: "business",
    },
  },
];

export default RECEIPT_POSTS;
