// English guides for internationals who work for themselves in the Netherlands.
// Same shape as POSTS in src/pages/Blog.jsx; each slug also has a /p/ rewrite in
// vercel.json and a sitemap entry so it is pre-rendered and discovered.

const FREE_CTA_EN = {
  title: "Start invoicing in English, for free",
  sub: "Free plan: 20 invoices and 5 clients. Work in English, send invoices in Dutch, English, French, Spanish or Arabic. No card needed.",
  button: "Create your free account →",
};

const ENGLISH_GUIDES = [
  {
    slug: "dutch-vat-btw-guide-expat-freelancers",
    lang: "en",
    title: "Dutch VAT (BTW) Explained for Expat Freelancers",
    seoTitle: "Dutch VAT (BTW) Guide for Expat Freelancers | FaturaPro",
    description: "BTW in plain English: the 21%, 9% and 0% rates, your two VAT numbers, quarterly returns and deadlines, reclaiming VAT on costs, the KOR scheme and reverse charge for EU clients.",
    date: "2026-10-09",
    readTime: "8 min",
    keywords: "Dutch VAT freelancer, BTW explained English, VAT Netherlands expat, ZZP VAT return, btw aangifte English, KOR small business scheme, reverse charge Netherlands, VAT rates Netherlands 21 9",
    quickAnswer: "As a freelancer in the Netherlands you usually add 21% VAT (BTW) to your invoices, file a VAT return every quarter and pay the balance by the end of the following month. You deduct the VAT you paid on business costs. With the KOR scheme (turnover up to €20,000 a year) you can choose not to charge VAT at all, but then you cannot reclaim it either.",
    checklist: [
      "Standard rate 21%, reduced rate 9%, and 0% or exempt in specific cases",
      "Your VAT ID (btw-id, NL…B01) goes on every invoice",
      "Quarterly return: deadline is the last day of the month after the quarter",
      "Deduct the VAT on your business costs (voorbelasting)",
      "EU business client: usually 'VAT reverse-charged' and their VAT ID on the invoice",
      "KOR: no VAT charged or reclaimed if turnover stays under €20,000 a year",
    ],
    sections: [
      { h: "What BTW Is", p: "BTW (belasting toegevoegde waarde) is the Dutch name for VAT. As a business you collect it from your clients on behalf of the Belastingdienst, the Dutch tax authority, and you pay it on what you buy for your business. Every quarter you settle the difference. The VAT on your invoices is never your income: it is money you hold for the tax authority." },
      { h: "The Rates: 21%, 9% and 0%", p: "Most services and products carry the standard rate of 21%. A reduced rate of 9% applies to things such as food, books, medicines and some repairs and services. A 0% rate applies, for example, to exports outside the EU and supplies of goods to VAT-registered businesses in other EU countries. Some activities are exempt altogether, such as most medical care and certain education. Exempt is not the same as 0%: with an exemption you also cannot reclaim VAT on your costs." },
      { h: "Your Two VAT Numbers", p: "After you register a sole proprietorship (eenmanszaak) with the KVK, the Belastingdienst sends you two numbers. The VAT identification number (btw-id, in the format NL000000000B01) is the one you put on your invoices and share with clients. The VAT tax number (omzetbelastingnummer) is for your returns and correspondence with the tax authority; keep it to yourself." },
      { h: "Quarterly Returns and Deadlines", p: "Most freelancers file every quarter. The return and the payment are due by the last day of the month after the quarter: 30 April for Q1, 31 July for Q2, 31 October for Q3 and 31 January for Q4. You file online in Mijn Belastingdienst Zakelijk, or your accountant does it for you. Filing or paying late can lead to a fine, so put the dates in your calendar. If you had no turnover in a quarter, you still file a return, showing zero." },
      { h: "Reclaiming VAT on Your Costs", p: "The VAT you pay on business purchases, such as a laptop, software subscriptions or a co-working desk, is called voorbelasting. You deduct it from the VAT you collected. If you paid more than you collected, the Belastingdienst refunds the difference. You need a proper invoice or receipt in your business name for each purchase, and the cost has to be for your business. Keep these records for 7 years." },
      { h: "The KOR Small Business Scheme", p: "With the kleineondernemersregeling (KOR) you do not charge VAT and you do not file VAT returns, as long as your turnover stays under €20,000 a year. That can make your prices more attractive for private clients. The downside: you cannot reclaim VAT on your costs, and once you join you stay in for at least three years unless your turnover goes over the limit. Compare both options before you apply." },
      { h: "Clients in Other EU Countries", p: "For most services to a VAT-registered business in another EU country, you do not charge Dutch VAT. Instead you write 'VAT reverse-charged' (btw verlegd) on the invoice, together with your client's VAT ID, and the client pays the VAT in their own country. You report these sales in your VAT return and in a separate listing (opgave ICP). Private clients abroad and clients outside the EU follow different rules, so check your situation or ask an accountant." },
      { h: "How FaturaPro Helps", p: "FaturaPro calculates the VAT on every invoice at the rate you choose, keeps currencies apart, and adds up the VAT on your sales and on your expenses per quarter. Scan a receipt and its VAT is filled in. At the end of the quarter you have the three numbers you need: VAT collected, VAT paid and the balance to pay or reclaim. You or your accountant then file the return." },
    ],
    faqs: [
      { q: "Do I have to charge VAT as a freelancer in the Netherlands?", a: "Usually yes, at 21% for most services. Exceptions are exempt activities, reverse-charge sales to EU businesses, and the KOR scheme for small turnovers." },
      { q: "When is the Q3 VAT return due?", a: "By 31 October: both the return and the payment. Q4 is due by 31 January." },
      { q: "Can my invoices be in English?", a: "Yes. An invoice does not have to be in Dutch, as long as it contains all the required details. The Belastingdienst can ask for a translation." },
      { q: "Does FaturaPro file my VAT return?", a: "No. It gives you the quarterly figures; you or your accountant file the return in Mijn Belastingdienst Zakelijk." },
    ],
    sources: [
      { label: "Business.gov.nl: VAT rates", href: "https://business.gov.nl/regulations/vat-rates/" },
      { label: "Business.gov.nl: filing a VAT return", href: "https://business.gov.nl/regulations/filing-vat-return/" },
      { label: "Business.gov.nl: small businesses scheme (KOR)", href: "https://business.gov.nl/subsidies-and-schemes/small-businesses-scheme-kor/" },
    ],
    relatedLinks: [
      { label: "How to invoice as a ZZP in the Netherlands", href: "/blog/how-to-invoice-zzp-netherlands-english" },
      { label: "Starting as a freelancer in the Netherlands", href: "/blog/start-freelancing-netherlands-checklist" },
      { label: "Receipt scanner for freelancers", href: "/blog/receipt-scanner-app-freelancers-netherlands" },
      { label: "How to invoice international clients", href: "/blog/how-to-invoice-international-clients" },
      { label: "Reverse charge VAT (btw verlegd) explained", href: "/blog/reverse-charge-vat-invoice-btw-verlegd" },
    ],
    cta: FREE_CTA_EN,
  },
  {
    slug: "how-to-invoice-zzp-netherlands-english",
    lang: "en",
    title: "How to Invoice as a ZZP in the Netherlands (English Guide)",
    seoTitle: "How to Invoice as a ZZP in the Netherlands | English Guide",
    description: "Everything a Dutch invoice must show, in English: numbering, your KVK number and VAT ID, VAT per rate, payment terms, the 15-day rule, credit notes and how long to keep invoices.",
    date: "2026-10-09",
    readTime: "7 min",
    keywords: "how to invoice ZZP Netherlands, Dutch invoice requirements English, invoice template Netherlands freelancer, factuur requirements English, KVK number on invoice, payment terms Netherlands, credit note Netherlands",
    quickAnswer: "A Dutch invoice needs a unique sequential number, the invoice date, your name, address, KVK number and VAT ID, your client's name and address, a description and date of the work, the amount excluding VAT, the VAT rate and amount, and the total. Send it within 15 days after the end of the month of the work, and set a payment term; without one, 30 days applies for business clients.",
    checklist: [
      "Unique, sequential invoice number",
      "Invoice date and date (or period) of the work",
      "Your name, address, KVK number and VAT ID",
      "Client's name and address (and VAT ID for reverse charge)",
      "Description, quantity and price per item",
      "Amount excl. VAT, VAT rate and VAT amount per rate, total",
    ],
    sections: [
      { h: "Can I Invoice in English?", p: "Yes. Dutch law does not require invoices to be in Dutch. Many freelancers in the Netherlands invoice in English, especially for international clients. What matters is that every required detail is there. The tax authority may ask for a translation, so keep your wording clear and simple." },
      { h: "What Every Invoice Must Show", p: "Your invoice needs: a unique invoice number in an unbroken sequence; the invoice date; your name and address; your VAT identification number; your client's name and address; a clear description of the work or goods with the quantity; the date or period of the work; the amount excluding VAT; the VAT rate and the VAT amount for each rate; and the total. As a business registered with the KVK you also show your KVK number." },
      { h: "Invoice Numbers", p: "Numbers must be unique and follow on from each other, for example 2026-001, 2026-002. You may start a new series each year. Do not reuse or skip numbers to hide a mistake: a wrong invoice is corrected with a credit note, not deleted." },
      { h: "When to Send It", p: "For business clients, the invoice must be issued no later than the 15th day of the month after the month in which you did the work. In practice it is best to invoice the day the job is done: the sooner it is sent, the sooner you get paid." },
      { h: "Payment Terms", p: "Put a payment term on every invoice, such as 14 or 30 days. If you agreed nothing, the legal term for business clients is 30 days. Large companies must pay small businesses and freelancers within 30 days at most. If a business client pays late, you may charge statutory commercial interest and collection costs; for private clients, send a 14-day reminder letter first." },
      { h: "Clients Abroad", p: "For an EU business client you usually do not charge Dutch VAT on services. Write 'VAT reverse-charged' on the invoice and add the client's VAT ID. For clients outside the EU, different rules apply depending on the service. Invoicing in the client's currency is fine: show the amounts clearly and keep the VAT figures correct." },
      { h: "Mistakes and Credit Notes", p: "Sent an invoice with an error? Do not change or delete it. Create a credit note with its own number that refers to the original invoice and cancels it, then send a new, correct invoice. This keeps your number sequence and your VAT return correct." },
      { h: "Keeping Invoices", p: "Keep copies of all invoices you send and receive for 7 years. Digital copies are fine, as long as they are complete and readable." },
      { h: "Doing It in FaturaPro", p: "In FaturaPro you work in English and pick the invoice language per client. Numbers follow on automatically, VAT is calculated per invoice, a credit note is one click, and invoices are kept with your account. You can add your logo, bank details and payment terms once and reuse them on every invoice." },
    ],
    faqs: [
      { q: "Is a KVK number required on an invoice?", a: "Businesses registered in the Dutch Commercial Register show their KVK number on invoices and other business documents." },
      { q: "What is the default payment term in the Netherlands?", a: "For business clients, 30 days if nothing else was agreed. Large companies may take at most 30 days to pay small businesses." },
      { q: "Can I send invoices in another currency?", a: "Yes. FaturaPro supports 18 currencies and keeps each currency apart in your overview." },
      { q: "How do I correct a sent invoice?", a: "With a credit note that refers to the original, followed by a new invoice. Never delete a sent invoice." },
    ],
    sources: [
      { label: "Business.gov.nl: invoice requirements", href: "https://business.gov.nl/regulations/invoice-requirements/" },
      { label: "Business.gov.nl: payment terms", href: "https://business.gov.nl/running-your-business/accounting-and-finance/payment-terms/" },
    ],
    relatedLinks: [
      { label: "Dutch VAT (BTW) explained", href: "/blog/dutch-vat-btw-guide-expat-freelancers" },
      { label: "English invoicing software for ZZP'ers", href: "/blog/zzp-invoice-app-english-netherlands" },
      { label: "How to create a professional invoice", href: "/blog/how-to-create-professional-invoice" },
      { label: "How to invoice international clients", href: "/blog/how-to-invoice-international-clients" },
    ],
    cta: FREE_CTA_EN,
  },
  {
    slug: "start-freelancing-netherlands-checklist",
    lang: "en",
    title: "Starting as a Freelancer in the Netherlands: A Checklist for Internationals",
    seoTitle: "Start Freelancing in the Netherlands: Checklist for Internationals",
    description: "The steps to work for yourself in the Netherlands as an international: your right to work, BSN, KVK registration, VAT numbers, bank account, insurance, tax deductions and records.",
    date: "2026-10-09",
    readTime: "8 min",
    keywords: "start freelancing Netherlands, become ZZP expat, register KVK English, eenmanszaak expat, freelance checklist Netherlands, self-employed Netherlands international, zelfstandigenaftrek English, urencriterium",
    quickAnswer: "Check that your residence status allows self-employment, make sure you have a BSN, register a sole proprietorship (eenmanszaak) with the KVK, wait for your VAT numbers from the Belastingdienst, open a separate business account, arrange insurance, and set up invoicing and record keeping from day one.",
    checklist: [
      "Residence status allows self-employment",
      "BSN (citizen service number)",
      "KVK registration as eenmanszaak",
      "VAT numbers from the Belastingdienst",
      "Separate business bank account",
      "Insurance, invoicing and records for 7 years",
    ],
    sections: [
      { h: "1. Check Your Right to Work for Yourself", p: "EU, EEA and Swiss citizens can work as freelancers in the Netherlands. If you have another nationality, check that your residence permit allows self-employment; some permits state that work is freely allowed, others do not. US and Japanese citizens can apply for a residence permit as self-employed under the Dutch-American (DAFT) or Dutch-Japanese treaty. When in doubt, check with the IND." },
      { h: "2. Get Your BSN", p: "Your citizen service number (BSN) is needed for almost everything, including registering your business. You receive it when you register at your municipality." },
      { h: "3. Register With the KVK", p: "Most freelancers start as a sole proprietorship (eenmanszaak). You register online at kvk.nl and usually confirm your identity at a short appointment at a KVK office. You choose a trade name, describe your activities and pay a one-off fee; check kvk.nl for the current amount. You receive your KVK number straight away." },
      { h: "4. Your VAT Numbers", p: "After registration the Belastingdienst sends you a VAT ID for your invoices and a VAT tax number for your returns, usually within about two weeks. From then on you add VAT to your invoices and file a return every quarter, unless you choose the KOR small business scheme." },
      { h: "5. Open a Business Account", p: "It is not legally required for a sole proprietorship, but a separate account keeps business and private money apart, makes your administration easier and looks more professional to clients." },
      { h: "6. Insurance", p: "Basic health insurance is compulsory for residents. As a freelancer, consider professional or general liability insurance, and think about disability insurance, because as self-employed you are not covered through an employer." },
      { h: "7. Tax Deductions for Entrepreneurs", p: "Your profit is taxed through your yearly income tax return. If you work at least 1,225 hours a year on your business (the hours criterion, urencriterium), you can qualify for the self-employed deduction (zelfstandigenaftrek), and in your first years for the starters deduction. Keep a simple log of your hours. An accountant can tell you what applies to you." },
      { h: "8. Invoicing and Records From Day One", p: "Send proper invoices with sequential numbers, keep every receipt and purchase invoice, and keep your records for 7 years. Set money aside for VAT and income tax as soon as you get paid. With FaturaPro you can invoice in English, scan receipts, see your VAT per quarter and give your accountant view-only access to everything." },
    ],
    faqs: [
      { q: "Do I need a Dutch business bank account?", a: "It is not required for a sole proprietorship, but it is strongly recommended to keep business and private money apart." },
      { q: "How long does it take to get a VAT number?", a: "Usually about two weeks after your KVK registration; the Belastingdienst sends it by post." },
      { q: "Can I use FaturaPro in English?", a: "Yes. The app works in English, Dutch, French, Spanish and Arabic, and you choose the language of each invoice." },
      { q: "Can my accountant see my invoices?", a: "Yes. Add your accountant to your team with view-only access: they see invoices, expenses and receipts, but cannot change anything." },
    ],
    sources: [
      { label: "KVK: registering a business", href: "https://www.kvk.nl/en/registration/" },
      { label: "Business.gov.nl: starting a business", href: "https://business.gov.nl/starting-your-business/" },
      { label: "IND: working in the Netherlands", href: "https://ind.nl/en/work" },
    ],
    relatedLinks: [
      { label: "Dutch VAT (BTW) explained", href: "/blog/dutch-vat-btw-guide-expat-freelancers" },
      { label: "How to invoice as a ZZP", href: "/blog/how-to-invoice-zzp-netherlands-english" },
      { label: "Compare Free, Essential and Advanced", href: "/blog/invoicing-plans-free-vs-pro-vs-business" },
    ],
    cta: FREE_CTA_EN,
  },
  {
    slug: "how-to-invoice-international-clients",
    lang: "en",
    title: "How to Invoice International Clients: Currency, VAT and Language",
    seoTitle: "How to Invoice International Clients (Currency & VAT) | FaturaPro",
    description: "A practical guide for freelancers billing clients abroad: which currency to use, when to charge VAT or reverse-charge it, what to put on the invoice, which language to write it in, and how to get paid.",
    date: "2026-10-09",
    readTime: "7 min",
    keywords: "invoice international clients, invoice foreign client, multi-currency invoice, invoice in USD freelancer, reverse charge invoice EU, invoice client outside EU VAT, freelancer international payments",
    quickAnswer: "Invoice an international client the same way as a local one, with three extra checks. Agree on the currency up front and put it on the invoice. Check the VAT: for business clients in another EU country you usually charge no VAT and write 'VAT reverse-charged' plus their VAT ID; for business clients outside the EU you usually charge no Dutch VAT either. And send the invoice in a language your client reads, with bank details that work across borders (IBAN and BIC).",
    checklist: [
      "Agree on the currency before you start and show it on every amount",
      "Business client in another EU country: check their VAT ID in VIES",
      "EU reverse charge: 0% VAT, the words 'VAT reverse-charged' and both VAT IDs on the invoice",
      "Business client outside the EU: usually no Dutch VAT on services",
      "Write the invoice in a language your client understands",
      "Add your IBAN and BIC, and agree who pays the bank fees",
      "Record foreign-currency income in euros in your own bookkeeping",
    ],
    sections: [
      { h: "Who This Guide Is For", p: "Freelancers and small businesses, especially in the Netherlands and the rest of the EU, who work for clients in other countries: a design agency in Germany, a start-up in the US, a shop in Dubai. The basics of a good invoice stay the same everywhere. What changes is the currency, the VAT treatment, the language and the way you get paid. The VAT rules below are general rules for business-to-business services from the Netherlands; goods, digital services to consumers and special sectors have their own rules, so check your situation with the Belastingdienst or an accountant." },
      { h: "Step 1: Agree on the Currency", p: "Decide with your client before the work starts which currency you will invoice in, and put it in your quote or contract. Invoicing in your client's currency (for example USD for a US client) is often easier for them to approve and pay, but you carry the exchange-rate risk: the amount that lands in your bank in euros can be lower than expected. Invoicing in euros moves that risk to your client. Whatever you choose, show the currency clearly on every amount, not just on the total, and keep it the same on reminders and credit notes. In FaturaPro you choose the currency per invoice from 18 currencies, and the dashboard shows your totals per currency side by side, without converting them." },
      { h: "Step 2: Charge VAT, or Reverse-Charge It", p: "For a business client in another EU country, services are usually taxed in the client's country through the reverse-charge mechanism. You charge 0% VAT, write 'VAT reverse-charged' (in Dutch: 'btw verlegd') on the invoice and add both your VAT ID and your client's VAT ID. First check the client's VAT ID in the EU's VIES database. In the Netherlands you also report these sales in your VAT return and in the ICP declaration (opgaaf intracommunautaire prestaties). For a business client outside the EU, services are usually not subject to Dutch VAT, so you charge no VAT and note that on the invoice. For private individuals the rules differ, and Dutch VAT often still applies. In FaturaPro you set the VAT percentage per invoice, so you can set it to 0% and put the reverse-charge text in the invoice notes." },
      { h: "Step 3: Put the Right Details on the Invoice", p: "An international invoice needs everything a local invoice needs: a unique invoice number, the invoice date, your name, address and VAT ID, your client's name and address, a clear description of the work with the date or period, the amounts, the VAT rate and amount, and the total. For EU reverse charge, add your client's VAT ID and the reverse-charge note. If you invoice in a foreign currency and do charge Dutch VAT, also state the VAT amount in euros. Missing details are one of the most common reasons an international invoice gets stuck in a client's approval process." },
      { h: "Step 4: Choose the Language", p: "There is no rule that an invoice from the Netherlands must be in Dutch. Use a language your client reads, so their finance team can approve it without questions; English works for most international clients. Some clients, especially public bodies and large companies, have their own requirements, so ask. FaturaPro lets you send each invoice in English, Dutch, French, Spanish or Arabic, while you keep working in your own language. Some clients also ask for an electronic invoice; FaturaPro can export a UBL/XML file in the EN 16931 format on paid plans, but it does not deliver invoices over the Peppol network itself." },
      { h: "Step 5: Make It Easy to Pay", p: "Add your IBAN and BIC (SWIFT) and the name on your account. Within the euro area a SEPA transfer is usually cheap and fast; payments from outside often go through intermediary banks that take a fee, so agree who pays those costs and consider a payment service that handles foreign currencies well. Set a clear due date, such as 14 or 30 days, and follow up as soon as an invoice is overdue. On the Advanced plan, clients can also pay FaturaPro invoices online by card through your own Stripe account." },
      { h: "Step 6: Keep Your Bookkeeping in Euros", p: "If you are based in the Netherlands, your bookkeeping and VAT return are in euros. Record each foreign-currency invoice in euros using a consistent exchange rate, for example the rate on the invoice date, and note the actual amount you received. The difference is an exchange-rate gain or loss. Your accountant can tell you which method to use. FaturaPro does not convert currencies, so you always see the amount you actually invoiced." },
    ],
    faqs: [
      { q: "Can I invoice in US dollars from the Netherlands?", a: "Yes. You may invoice in any currency you agree with your client. If you charge Dutch VAT on that invoice, also state the VAT amount in euros, and record the income in euros in your bookkeeping." },
      { q: "Do I charge VAT to a client in another EU country?", a: "For business clients with a valid VAT ID, services are usually reverse-charged: 0% VAT, the note 'VAT reverse-charged' and both VAT IDs on the invoice. For private individuals, Dutch VAT often still applies." },
      { q: "Do I charge VAT to a client in the US or UK?", a: "For business clients outside the EU, services are usually not subject to Dutch VAT. Check your specific service with the Belastingdienst or an accountant, as there are exceptions." },
      { q: "Does my invoice have to be in Dutch?", a: "No. Use a language your client understands. English is common for international clients." },
      { q: "Can FaturaPro send invoices over Peppol?", a: "No. FaturaPro can export a UBL/XML file in the EN 16931 format on paid plans, which your client or an access point can process, but FaturaPro is not a Peppol access point." },
    ],
    sources: [
      { label: "Belastingdienst: invoice requirements", href: "https://www.belastingdienst.nl/wps/wcm/connect/en/vat/content/invoicing-with-vat" },
      { label: "Your Europe: VAT rules for services", href: "https://europa.eu/youreurope/business/taxation/vat/cross-border-vat/index_en.htm" },
      { label: "European Commission: VIES VAT number check", href: "https://ec.europa.eu/taxation_customs/vies/" },
    ],
    relatedLinks: [
      { label: "Reverse charge VAT (btw verlegd) explained", href: "/blog/reverse-charge-vat-invoice-btw-verlegd" },
      { label: "Dutch VAT (BTW) explained", href: "/blog/dutch-vat-btw-guide-expat-freelancers" },
      { label: "Free invoice generator", href: "/invoice-generator" },
    ],
    cta: FREE_CTA_EN,
  },
  {
    slug: "reverse-charge-vat-invoice-btw-verlegd",
    lang: "en",
    title: "Reverse Charge VAT (btw verlegd): When to Use It and What to Put on Your Invoice",
    seoTitle: "Reverse Charge VAT (btw verlegd) Explained for Freelancers | FaturaPro",
    description: "When you charge 0% VAT and write 'VAT reverse-charged' on an invoice, what the invoice must show, where it goes in your Dutch VAT return, and how reverse charge works on costs you buy abroad.",
    date: "2026-10-09",
    readTime: "8 min",
    keywords: "reverse charge VAT, btw verlegd, VAT reverse charged invoice, reverse charge EU services, btw verlegd factuur, ICP opgaaf, reverse charge Netherlands freelancer, intra-community services VAT",
    quickAnswer: "Reverse charge means your client pays the VAT instead of you. As a Dutch freelancer you mostly use it when you sell services to a business with a valid VAT ID in another EU country: you charge 0% VAT, write 'VAT reverse-charged' (btw verlegd) on the invoice and add both VAT IDs. You report the sale in box 3b of your VAT return and in the ICP declaration. It also works the other way round: on services you buy from EU suppliers, such as online advertising, you declare the VAT yourself and usually deduct it in the same return.",
    checklist: [
      "Client is a business in another EU country with a valid VAT ID (check it in VIES)",
      "0% VAT and no VAT amount on the invoice",
      "The words 'VAT reverse-charged' or 'btw verlegd'",
      "Your VAT ID and your client's VAT ID",
      "Send the invoice by the 15th of the month after the work",
      "Report the turnover in box 3b and in the ICP declaration",
      "Costs from EU suppliers with reverse charge: box 4b, then deduct in box 5b",
    ],
    sections: [
      { h: "What Reverse Charge Means", p: "Normally you add VAT to your invoice, your client pays it to you, and you pay it to the tax authority. With reverse charge (in Dutch: btw verlegd, 'VAT shifted'), that obligation moves to your client. You send an invoice without VAT, and your client declares the VAT in their own country's return. A business client can usually deduct that VAT straight away, so for them it is often a zero-sum entry. Nothing is lost: the VAT is simply paid where the service is used. This guide covers the common situations for Dutch freelancers and small businesses. VAT has many exceptions, so check your own case with the Belastingdienst or an accountant." },
      { h: "When You Use It: Services to EU Businesses", p: "The most common case: you sell a service, such as design, development, consulting, marketing or translation, to a business in another EU country that has a valid VAT ID. Under the EU's general rule, a business-to-business service is taxed in the client's country, and the client applies the reverse charge. Before you invoice without VAT, check your client's VAT ID in the EU's VIES database and keep a screenshot or the confirmation. If the number is not valid, or the client is a private person, the reverse charge does not apply and you usually charge Dutch VAT." },
      { h: "When You Don't Use It", p: "Reverse charge is not a choice and not a discount. You do not use it for clients in the Netherlands (with a few exceptions below), for private individuals in other EU countries, or for clients without a valid VAT ID. Some services also follow their own rules regardless of who the client is, for example services related to property, admission to events, passenger transport and restaurant services; these are usually taxed where they take place. Clients outside the EU are a separate case: business-to-business services to them are usually not subject to Dutch VAT at all, but that is not an EU reverse charge, so do not write 'btw verlegd' and do not report it in the ICP declaration. Mention instead that the service is not subject to Dutch VAT." },
      { h: "What the Invoice Must Show", p: "A reverse-charge invoice contains everything a normal invoice needs, plus three things: the words 'VAT reverse-charged' (or 'btw verlegd', or 'Reverse charge'; any EU language is fine), your client's VAT ID next to your own, and a VAT amount of zero. Show the net amount as the total. A short example of the note: 'VAT reverse-charged (Art. 196 Council Directive 2006/112/EC). Client VAT ID: DE123456789.' For services to another EU country, send the invoice no later than the 15th day of the month after the month in which you did the work. In FaturaPro, set the VAT for that invoice to 0% and put the reverse-charge text and your client's VAT ID in the invoice notes; your own VAT ID comes from your business details." },
      { h: "Where It Goes in Your Dutch VAT Return", p: "Report the amount, without VAT, in box 3b of your Dutch VAT return ('Supplies to or services in countries within the EU'). You also file the ICP declaration (opgaaf intracommunautaire prestaties), which lists per client VAT ID how much you invoiced with reverse charge. Most freelancers file it every quarter, with the same deadline as the VAT return. The tax authorities compare your ICP declaration with your clients' returns, so make sure the VAT IDs and amounts match your invoices." },
      { h: "The Other Way Round: Costs You Buy from Abroad", p: "Reverse charge also applies when you are the client. Many tools freelancers use are invoiced from other EU countries with VAT reverse-charged, for example online advertising or software subscriptions billed from Ireland. Give those suppliers your VAT ID so they invoice without VAT. You then declare the Dutch VAT on that cost yourself in box 4b, and, if you can fully deduct VAT, deduct the same amount in box 5b. The result is usually zero, but the entries must be there. For services bought from outside the EU, the same works through box 4a. If you use the small business scheme (KOR), check with the Belastingdienst how this applies to you, as you may still owe reverse-charged VAT on services you buy abroad." },
      { h: "Reverse Charge Within the Netherlands", p: "There is also a domestic reverse charge for specific sectors, such as subcontracting in construction, the supply of certain staff, and some goods like scrap metal and, above a threshold, mobile phones and computer chips. Most freelancers in creative, IT or consulting work never use it. If you work in one of these sectors, ask your accountant which rules apply." },
    ],
    faqs: [
      { q: "Is 'btw verlegd' the same as 0% VAT?", a: "On the invoice both show no VAT, but they are different. With 0% (for example on an intra-EU supply of goods or an export) no VAT is due. With reverse charge, VAT is due, but your client declares and pays it instead of you." },
      { q: "Can I write 'VAT reverse-charged' in English?", a: "Yes. The note can be in any EU language. 'VAT reverse-charged', 'Reverse charge' and 'btw verlegd' are all fine." },
      { q: "What if my client's VAT ID is not valid?", a: "Then the reverse charge usually does not apply and you charge Dutch VAT. Always check the number in VIES before you invoice, and keep proof of the check." },
      { q: "Do I need to file the ICP declaration?", a: "Yes, if you invoiced services or goods with reverse charge or 0% to businesses in other EU countries in that period." },
      { q: "Does FaturaPro have a reverse-charge setting?", a: "There is no separate switch. Set the VAT on the invoice to 0% and add the reverse-charge note and your client's VAT ID in the invoice notes." },
    ],
    sources: [
      { label: "Belastingdienst: VAT reverse-charge mechanism", href: "https://www.belastingdienst.nl/wps/wcm/connect/en/vat/content/vat-reverse-charge-mechanism" },
      { label: "Your Europe: cross-border VAT", href: "https://europa.eu/youreurope/business/taxation/vat/cross-border-vat/index_en.htm" },
      { label: "European Commission: VIES VAT number check", href: "https://ec.europa.eu/taxation_customs/vies/" },
    ],
    relatedLinks: [
      { label: "How to invoice international clients", href: "/blog/how-to-invoice-international-clients" },
      { label: "Dutch VAT (BTW) explained", href: "/blog/dutch-vat-btw-guide-expat-freelancers" },
      { label: "Free invoice generator", href: "/invoice-generator" },
    ],
    cta: FREE_CTA_EN,
  },
];

export default ENGLISH_GUIDES;
