import { useEffect, useState } from "react";
import { approveAmbassador, fetchAmbassadorAdmin, updateAmbassador } from "../lib/ambassadors";

const CSS = `
  .adm{min-height:100vh;background:#08080e;color:#e8e4dc;font-family:'DM Sans',sans-serif}.admwrap{width:min(100% - 32px,1160px);margin:auto}.admnav{height:72px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.07)}.admnav a{color:#aaa49b;text-decoration:none;font-size:12px}.admnav strong{font:700 20px 'Playfair Display',serif}.admmain{padding:44px 0 90px}.admkicker{color:#c9a84c;text-transform:uppercase;font-size:10px;font-weight:800;letter-spacing:1.6px}.admtitle{font:700 43px 'Playfair Display',serif;margin:10px 0 32px}.admsection{margin-top:28px}.admsection h2{font:700 25px 'Playfair Display',serif;margin-bottom:14px}.admlist{display:grid;gap:12px}.admcard{padding:20px;border:1px solid rgba(255,255,255,.08);border-radius:14px;background:#111118}.admcardtop{display:flex;justify-content:space-between;gap:20px}.admcard h3{margin:0 0 4px;font-size:15px}.admmuted{color:#827d76;font-size:11px;line-height:1.6}.admbadge{height:max-content;padding:6px 9px;border:1px solid rgba(201,168,76,.25);border-radius:99px;color:#d9bb68;background:rgba(201,168,76,.06);font-size:9px;font-weight:800;text-transform:uppercase}.admprofile{color:#c9a84c}.admwhy{margin:13px 0;color:#aaa49b;font-size:12px;line-height:1.65}.admterms{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:15px}.admfield label{display:block;margin-bottom:5px;color:#77726c;font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.5px}.admfield select,.admfield input{width:100%;padding:10px;border:1px solid rgba(255,255,255,.1);border-radius:8px;background:#0b0b11;color:#e8e4dc}.admactions{display:flex;gap:9px;align-items:center;margin-top:13px;flex-wrap:wrap}.admbtn{padding:10px 13px;border:0;border-radius:8px;background:#c9a84c;color:#08080e;font-weight:800;font-size:11px;cursor:pointer}.admbtn.secondary{background:transparent;border:1px solid rgba(255,255,255,.13);color:#d6d0c7}.admbtn.danger{background:rgba(220,80,80,.1);border:1px solid rgba(220,80,80,.25);color:#ef9999}.admbtn:disabled{opacity:.5}.admerror{padding:12px;border:1px solid rgba(220,80,80,.28);border-radius:9px;background:rgba(220,80,80,.07);color:#ef9999;font-size:12px;margin-bottom:14px}.admstats{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-top:15px}.admstat{padding:11px;border-radius:9px;background:#0b0b11}.admstat span{display:block;color:#6f6a64;font-size:9px;text-transform:uppercase}.admstat b{display:block;margin-top:5px;font:700 18px 'Playfair Display',serif}.admempty{padding:25px;border:1px dashed rgba(255,255,255,.1);border-radius:12px;color:#77726c;text-align:center;font-size:12px}@media(max-width:700px){.admterms,.admstats{grid-template-columns:1fr 1fr}.admcardtop{flex-direction:column}}`;

function money(cents) { return new Intl.NumberFormat("en-IE", { style:"currency", currency:"EUR" }).format(Number(cents || 0) / 100); }
function shortDate(value) { return value ? new Date(value).toLocaleDateString("en-GB") : "—"; }

function ApplicationCard({ application, onApproved }) {
  const [terms, setTerms] = useState({ commissionPercent:25, commissionMonths:12, agreementMonths:12 });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const approve = async () => {
    setBusy(true); setError("");
    try { await approveAmbassador(application.id, terms); await onApproved(); }
    catch (err) { setError(err.message); setBusy(false); }
  };
  return <article className="admcard"><div className="admcardtop"><div><h3>{application.name}</h3><div className="admmuted">{application.email} · {application.primary_channel} · {application.audience_size} · {application.country}</div></div><span className="admbadge">{application.status}</span></div><p className="admwhy">{application.motivation}</p><a className="admprofile admmuted" href={application.profile_url} target="_blank" rel="noreferrer">Open public profile →</a>{application.status !== "approved" && <><div className="admterms"><div className="admfield"><label>Cash commission</label><select value={terms.commissionPercent} onChange={e => setTerms({ ...terms, commissionPercent:Number(e.target.value) })}><option value="25">25%</option><option value="30">30%</option><option value="35">35%</option></select></div><div className="admfield"><label>Earns per customer</label><select value={terms.commissionMonths} onChange={e => setTerms({ ...terms, commissionMonths:Number(e.target.value) })}><option value="6">6 months</option><option value="12">12 months</option><option value="18">18 months</option><option value="24">24 months</option></select></div><div className="admfield"><label>Partnership duration</label><select value={terms.agreementMonths} onChange={e => setTerms({ ...terms, agreementMonths:Number(e.target.value) })}><option value="6">6 months</option><option value="12">12 months</option><option value="18">18 months</option><option value="24">24 months</option></select></div></div><div className="admactions"><button className="admbtn" disabled={busy} onClick={approve}>{busy ? "Approving…" : "Approve with these terms"}</button><span className="admmuted">Applicant must have a Fatūra Pro account with this email.</span></div>{error && <div className="admerror" style={{ marginTop:12, marginBottom:0 }}>{error}</div>}</>}</article>;
}

export default function Admin() {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  const [busyId, setBusyId] = useState("");
  const load = async () => { try { setData(await fetchAmbassadorAdmin()); setError(""); } catch (err) { setError(err.message); } };
  useEffect(() => { load(); }, []);
  const status = async (account, next) => {
    setBusyId(account.id); setError("");
    try { await updateAmbassador(account.id, { status:next }); await load(); }
    catch (err) { setError(err.message); }
    setBusyId("");
  };
  return <div className="adm"><style>{CSS}</style><header className="admwrap admnav"><strong>Fatūra Pro · Partner control</strong><a href="/app">Open app →</a></header><main className="admwrap admmain"><div className="admkicker">Private administration</div><h1 className="admtitle">Ambassadors</h1>{error && <div className="admerror">{error}</div>}
    <section className="admsection"><h2>Applications</h2><div className="admlist">{data?.applications?.length ? data.applications.map(item => <ApplicationCard key={item.id} application={item} onApproved={load} />) : <div className="admempty">{data ? "No applications yet." : "Loading applications…"}</div>}</div></section>
    <section className="admsection"><h2>Active partnerships</h2><div className="admlist">{data?.accounts?.length ? data.accounts.map(account => <article className="admcard" key={account.id}><div className="admcardtop"><div><h3>{account.code}</h3><div className="admmuted">{account.commission_bps / 100}% for {account.commission_months} months/customer · Ends {shortDate(account.agreement_ends_at)}</div></div><span className="admbadge">{account.status}</span></div><div className="admstats"><div className="admstat"><span>Clicks</span><b>{account.clicks}</b></div><div className="admstat"><span>Sign-ups</span><b>{account.signups}</b></div><div className="admstat"><span>Paid customers</span><b>{account.customers}</b></div><div className="admstat"><span>Pending</span><b>{money((account.ledger.pending || 0) + (account.ledger.available || 0) + (account.ledger.processing || 0))}</b></div><div className="admstat"><span>Paid</span><b>{money(account.paid_out_cents)}</b></div></div><div className="admactions">{account.status === "active" ? <button className="admbtn secondary" disabled={busyId === account.id} onClick={() => status(account,"paused")}>Pause</button> : account.status === "paused" ? <button className="admbtn" disabled={busyId === account.id} onClick={() => status(account,"active")}>Resume</button> : null}{account.status !== "ended" && <button className="admbtn danger" disabled={busyId === account.id} onClick={() => status(account,"ended")}>End now</button>}<span className="admmuted">Payout: {account.payouts_enabled ? "connected · automatic" : "waiting for Stripe connection"}</span></div></article>) : <div className="admempty">{data ? "No approved ambassadors yet." : "Loading partnerships…"}</div>}</div></section>
  </main></div>;
}
